### ISSUE TITLE
Práctica final de Hilos en C#

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-final-de-hilos-prototipoxd#2]
[Práctica final de hilos.pdf](https://github.com/SistemasTecTlaxiaco/practica-final-de-hilos-prototipoxd/files/6497813/Practica.final.de.hilos.pdf)

**Comment by CxrlosMX** [comment]
Excelente trabajo compañeros
Porcentaje obtenido: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
